apiVersion: v1
kind: Pod
metadata:
  name: hello-world-sleeper
  namespace: default
spec:
  containers:
  - name: hello
    image: busybox
    command: ["/bin/sh", "-c"]
    args: ["echo Hello, world; sleep 10000"]

