apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- ../../shared/flux-kustomizations/cert-manager.yaml
- ../../shared/flux-kustomizations/cluster-issuer.yaml